/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_hpk_Differentiator */

#ifndef _Included_de_hpk_Differentiator
#define _Included_de_hpk_Differentiator
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_hpk_Differentiator
 * Method:    test
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_de_hpk_Differentiator_test
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
